### ISSUE TITLE
DropBox integration

### ISSUE THREAD

**Issue by t-pankajkumar** [jpillora/cloud-torrent#22]
Is it possible to integrate dropbox (or any) into this application so that we can overcome heroku dyno server issue.
Thank you .

**Comment by jpillora** [comment]
Yep it is possible, I just need to find the time

**Comment by jaswinder-singh** [comment]
i'd love to see google drive because of its free 15gb...

**Comment by t-pankajkumar** [comment]
@jpillora or cold you tell us which file writes the bytes to file, so that we try to implement this feature.

**Comment by jaswinder-singh** [comment]
yeah agreed

**Comment by jpillora** [comment]
File writing is handled by anacrolix/torrent

The engine package controls anacrolix/torrent so that package would need to
be updated to write to a buffer which is then uploaded as it downloads.

This would also need front-end to manage Dropbox token, or even better, a
login to Dropbox button which retrieves an oauth token.

**Comment by jpillora** [comment]
Made a new more generic issue for this #24
